Added support for K8s, including NGINX with ngx_upstream_jdomain.

diff --git a/Dockerfile-nginx b/Dockerfile-nginx
--- a/Dockerfile-nginx
+++ b/Dockerfile-nginx
@@ -1,40 +1,186 @@
-FROM nginx
+FROM alpine:3.5
 
-# Install dependencies
-RUN apt-get update -qq && apt-get -y install apache2-utils
+LABEL maintainer="NGINX Docker Maintainers <docker-maint@nginx.com>"
 
-# establish where Nginx should look for files
-ENV WWW_ROOT /var/www/app/
+ENV NGINX_VERSION 1.13.7
 
+RUN GPG_KEYS=B0F4253373F8F6F510D42178520A9993A1C052F8 \
+  && CONFIG="\
+    --prefix=/etc/nginx \
+    --sbin-path=/usr/sbin/nginx \
+    --modules-path=/usr/lib/nginx/modules \
+    --conf-path=/etc/nginx/nginx.conf \
+    --error-log-path=/var/log/nginx/error.log \
+    --http-log-path=/var/log/nginx/access.log \
+    --pid-path=/var/run/nginx.pid \
+    --lock-path=/var/run/nginx.lock \
+    --http-client-body-temp-path=/var/cache/nginx/client_temp \
+    --http-proxy-temp-path=/var/cache/nginx/proxy_temp \
+    --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
+    --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp \
+    --http-scgi-temp-path=/var/cache/nginx/scgi_temp \
+    --user=nginx \
+    --group=nginx \
+    --with-http_ssl_module \
+    --with-http_realip_module \
+    --with-http_addition_module \
+    --with-http_sub_module \
+    --with-http_dav_module \
+    --with-http_flv_module \
+    --with-http_mp4_module \
+    --with-http_gunzip_module \
+    --with-http_gzip_static_module \
+    --with-http_random_index_module \
+    --with-http_secure_link_module \
+    --with-http_stub_status_module \
+    --with-http_auth_request_module \
+    --with-http_xslt_module=dynamic \
+    --with-http_image_filter_module=dynamic \
+    --with-http_geoip_module=dynamic \
+    --with-http_perl_module=dynamic \
+    --with-threads \
+    --with-stream \
+    --with-stream_ssl_module \
+    --with-stream_ssl_preread_module \
+    --with-stream_realip_module \
+    --with-stream_geoip_module=dynamic \
+    --with-http_slice_module \
+    --with-mail \
+    --with-mail_ssl_module \
+    --with-compat \
+    --with-file-aio \
+    --with-http_v2_module \
+    --with-ipv6 \
+    --add-module=/usr/src/ngx_upstream_jdomain \
+  " \
+  && addgroup -S nginx \
+  && adduser -D -S -h /var/cache/nginx -s /sbin/nologin -G nginx nginx \
+  && apk add --no-cache --virtual .build-deps \
+    gcc \
+    git \
+    libc-dev \
+    make \
+    openssl-dev \
+    pcre-dev \
+    zlib-dev \
+    linux-headers \
+    curl \
+    gnupg \
+    libxslt-dev \
+    gd-dev \
+    geoip-dev \
+    perl-dev \
+  && curl -fSL http://nginx.org/download/nginx-$NGINX_VERSION.tar.gz -o nginx.tar.gz \
+  && curl -fSL http://nginx.org/download/nginx-$NGINX_VERSION.tar.gz.asc  -o nginx.tar.gz.asc \
+  && export GNUPGHOME="$(mktemp -d)" \
+  && found=''; \
+  for server in \
+    ha.pool.sks-keyservers.net \
+    hkp://keyserver.ubuntu.com:80 \
+    hkp://p80.pool.sks-keyservers.net:80 \
+    pgp.mit.edu \
+  ; do \
+    echo "Fetching GPG key $GPG_KEYS from $server"; \
+    gpg --keyserver "$server" --keyserver-options timeout=10 --recv-keys "$GPG_KEYS" && found=yes && break; \
+  done; \
+  test -z "$found" && echo >&2 "error: failed to fetch GPG key $GPG_KEYS" && exit 1; \
+  gpg --batch --verify nginx.tar.gz.asc nginx.tar.gz \
+  && rm -r "$GNUPGHOME" nginx.tar.gz.asc \
+  && mkdir -p /usr/src \
+  && tar -zxC /usr/src -f nginx.tar.gz \
+  && rm nginx.tar.gz \
+  && git clone git://github.com/arobson/ngx_upstream_jdomain /usr/src/ngx_upstream_jdomain \
+  && cd /usr/src/nginx-$NGINX_VERSION \
+  && ./configure $CONFIG --with-debug \
+  && make -j$(getconf _NPROCESSORS_ONLN) \
+  && mv objs/nginx objs/nginx-debug \
+  && mv objs/ngx_http_xslt_filter_module.so objs/ngx_http_xslt_filter_module-debug.so \
+  && mv objs/ngx_http_image_filter_module.so objs/ngx_http_image_filter_module-debug.so \
+  && mv objs/ngx_http_geoip_module.so objs/ngx_http_geoip_module-debug.so \
+  && mv objs/ngx_http_perl_module.so objs/ngx_http_perl_module-debug.so \
+  && mv objs/ngx_stream_geoip_module.so objs/ngx_stream_geoip_module-debug.so \
+  && ./configure $CONFIG \
+  && make -j$(getconf _NPROCESSORS_ONLN) \
+  && make install \
+  && rm -rf /etc/nginx/html/ \
+  && mkdir /etc/nginx/conf.d/ \
+  && mkdir -p /usr/share/nginx/html/ \
+  && install -m644 html/index.html /usr/share/nginx/html/ \
+  && install -m644 html/50x.html /usr/share/nginx/html/ \
+  && install -m755 objs/nginx-debug /usr/sbin/nginx-debug \
+  && install -m755 objs/ngx_http_xslt_filter_module-debug.so /usr/lib/nginx/modules/ngx_http_xslt_filter_module-debug.so \
+  && install -m755 objs/ngx_http_image_filter_module-debug.so /usr/lib/nginx/modules/ngx_http_image_filter_module-debug.so \
+  && install -m755 objs/ngx_http_geoip_module-debug.so /usr/lib/nginx/modules/ngx_http_geoip_module-debug.so \
+  && install -m755 objs/ngx_http_perl_module-debug.so /usr/lib/nginx/modules/ngx_http_perl_module-debug.so \
+  && install -m755 objs/ngx_stream_geoip_module-debug.so /usr/lib/nginx/modules/ngx_stream_geoip_module-debug.so \
+  && ln -s ../../usr/lib/nginx/modules /etc/nginx/modules \
+  && strip /usr/sbin/nginx* \
+  && strip /usr/lib/nginx/modules/*.so \
+  && rm -rf /usr/src/nginx-$NGINX_VERSION \
+  \
+  # Bring in gettext so we can get `envsubst`, then throw
+  # the rest away. To do this, we need to install `gettext`
+  # then move `envsubst` out of the way so `gettext` can
+  # be deleted completely, then move `envsubst` back.
+  && apk add --no-cache --virtual .gettext gettext \
+  && mv /usr/bin/envsubst /tmp/ \
+  \
+  && runDeps="$( \
+    scanelf --needed --nobanner --format '%n#p' /usr/sbin/nginx /usr/lib/nginx/modules/*.so /tmp/envsubst \
+      | tr ',' '\n' \
+      | sort -u \
+      | awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
+  )" \
+  && apk add --no-cache --virtual .nginx-rundeps $runDeps
+
+  # *** BUILD CUSTOM MODULE HERE ***
+  RUN cd /usr/src/ngx_upstream_jdomain \
+      make \
+      make install
+
+  RUN apk del .build-deps \
+  && apk del .gettext \
+  && mv /tmp/envsubst /usr/local/bin/ \
+  \
+  # forward request and error logs to docker log collector
+  && ln -sf /dev/stdout /var/log/nginx/access.log \
+  && ln -sf /dev/stderr /var/log/nginx/error.log \
+  && rm -rf /usr/src/ngx_upstream_jdomain
+
+RUN mkdir /etc/nginx/sites-available
+COPY nginx.conf /etc/nginx/nginx.conf
+COPY nginx.vh.default.conf /etc/nginx/sites-available/default.conf
+RUN ln -s /etc/nginx/sites-available/default.conf /etc/nginx/conf.d
+
+EXPOSE 80 443
+
+STOPSIGNAL SIGTERM
+
+# Setup for Rails SSL proxy
+# Copy NGINX template certificates
+RUN mkdir -p /etc/nginx/ssl/
+COPY rubysite/ssl /etc/nginx/ssl/
+RUN chmod 700 /etc/nginx/ssl/private/
+# Establish where Nginx should look for files
+ENV WWW_ROOT /usr/share/nginx/
+# Establish resolver
+ENV CONTAINER_RESOLVER 127.0.0.11
+# Establish local domain for upstream
+#ENV CONTAINER_LOCALDOMAIN
+# Copy NGINX config template
+COPY rubysite/nginx.conf /etc/nginx/sites-available/rubysite.template
+# substitute variable references in the NGINX config template for real values from the environment
+# put the final config in its place
+RUN envsubst '$WWW_ROOT:$CONTAINER_RESOLVER:$CONTAINER_LOCALDOMAIN' < /etc/nginx/sites-available/rubysite.template > /etc/nginx/sites-available/rubysite.conf
+RUN ln -s /etc/nginx/sites-available/rubysite.conf /etc/nginx/conf.d
+RUN rm /etc/nginx/conf.d/default.conf
 # Set our working directory inside the image
 WORKDIR $WWW_ROOT
-
-# create log directory
+# Create log directory
 RUN mkdir log
-
-# create public directory
+# Create public directory
 RUN mkdir public
-
-# copy over static assets
+# Copy over static assets
 # COPY public public/
 
-# Copy Nginx template certificates
-RUN mkdir -p /etc/nginx/ssl/
-COPY nginx/ssl /etc/nginx/ssl/
-RUN chmod 700 /etc/nginx/ssl/private/
-
-# Copy Nginx config template
-COPY nginx/nginx.conf /tmp/docker_example.nginx
-
-# substitute variable references in the Nginx config template for real values from the environment
-# put the final config in its place
-RUN mkdir /etc/nginx/sites-available
-RUN envsubst '$WWW_ROOT' < /tmp/docker_example.nginx > /etc/nginx/sites-available/rubysite.conf
-RUN ln -s /etc/nginx/sites-available/rubysite.conf /etc/nginx/conf.d
-RUN rm -f /tmp/docker_example.nginx
-RUN mv /etc/nginx/conf.d/default.conf /etc/nginx/sites-available
-
-EXPOSE 80
-
-# Use the "exec" form of CMD so Nginx shuts down gracefully on SIGTERM (i.e. `docker stop`)
-CMD [ "nginx", "-g", "daemon off;" ]
+CMD ["nginx", "-g", "daemon off;"]
